apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: user-service
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-service
  template:
    metadata:
      labels:
        io.kompose.service: user-service
    spec:
      containers:
      - env:
        - name: RDS_DB_NAME
          value: todos
        - name: RDS_HOSTNAME
          value: mysql
        - name: RDS_PASSWORD
          value: root
        - name: RDS_PORT
          value: "3306"
        - name: RDS_USERNAME
          value: root
        image: ishugarg34/user-service:tag1
        imagePullPolicy: ""
        name: user-service
        ports:
        - containerPort: 8080
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
